### ISSUE TITLE
update to actual version

### ISSUE THREAD

**Issue by deviator** [tchaloupka/during#1]
Hi, @tchaloupka!
do you plane update this library for newer kernel version (5.7 for example)?

**Comment by tchaloupka** [comment]
Hi, sure will, only need to find some spare time to do it ;-)

**Comment by tchaloupka** [comment]
Partially fixed in 604f1588938d69c2b55a1fd3267bf7c4dc95d894.
Just definitions though, no helper functions or tests yet.

**Comment by tchaloupka** [comment]
Just released new version, there should available everything that is defined on the kernel side including prep methods for new operations.

Tests are still missing, but I guess better release this and hope it's already tested in liburing than wait ;-)
