### ISSUE TITLE
Write/read barriers

### ISSUE THREAD

**Issue by Boris-Barboris** [tchaloupka/during#6]
liburing is conforming to memory ordering requirements of the kernel using it's hefty _o_uring_smp_._.. inline functions.   
https://github.com/axboe/liburing/blob/master/src/queue.c#L223
https://github.com/axboe/liburing/blob/master/src/queue.c#L387
https://github.com/axboe/liburing/blob/master/src/queue.c#L53
https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/src/include/liburing/barrier.h#L8
Didn't notice anything like it in during.

**Comment by tchaloupka** [comment]
Hi, it's implemented using atomic ops from `core.atomic`.
For example:
* https://github.com/tchaloupka/during/blob/fda8724723f0ed0e247437df6c348301e7f9e078/source/during/package.d#L1260
* https://github.com/tchaloupka/during/blob/fda8724723f0ed0e247437df6c348301e7f9e078/source/during/package.d#L1272

At first io_uring haven't used atomics but some custom asm implementation: see https://github.com/axboe/liburing/commit/b9c0bf79aa879727f55f4fe7333dd41bebd0acd4
and that was too much magic for me so I've got inspired from some other wrapper implementations and went with `core.atomic`.

But haven't checked that afterwards so there might be some differences. Although we're using it in production (sockets + file ops) and have problems only with some kernel versions as fixes takes pretty long to get to distribution kernels and io_uring development is still way too active.

**Comment by Boris-Barboris** [comment]
Thx, good to know
