### ISSUE TITLE
remove static assert "during is not available on this system"

### ISSUE THREAD

**Issue by skoppe** [tchaloupka/during#7]
First off, this is lovely. I have plans to integrate uring into the [concurrency](https://github.com/symmetryinvestments/concurrency) library and build servers based on that.

I'll probably have to support windows iocp too, and the [static assert](https://github.com/tchaloupka/during/blob/29d47b6d4d5ebc54bf2f3fcc2767e8b29b2cbfd8/source/during/package.d) would be giving trouble.

Would you consider to refactor to just `version(linux):` ?

In any case, thanks for a good library.

**Comment by tchaloupka** [comment]
Hi @skoppe, sure thing, probably no big reason to be this strict, it won't work anyway. I'll make the release shortly as kernel 5.15 is already out and there are no more changes in `io_uring` interface.
